language: node_js
sudo: false

node_js:
  - "4.3"
  - "5"

env:
  - KAFKA_HOME=../kafka CXX=g++-4.8

before_install:
- wget http://www.us.apache.org/dist/kafka/0.8.2.2/kafka_2.10-0.8.2.2.tgz -O kafka.tgz
- mkdir -p ${KAFKA_HOME} && tar xzf kafka.tgz -C ${KAFKA_HOME} --strip-components 1
- echo 'delete.topic.enable=true' >> ${KAFKA_HOME}/config/server.properties
- nohup bash -c "cd ${KAFKA_HOME} && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- nohup bash -c "cd ${KAFKA_HOME} && bin/kafka-server-start.sh config/server.properties &"
- sleep 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: npm run coverage && (npm run coveralls || exit 0)
