num_workers: 0
logging:
  name: changeprop
  level: info
services:
  - name: changeprop
    module: hyperswitch
    conf:
      port: 7273
      spec:
        title: The Change Propagation root
        paths:
          /sys/queue:
            x-modules:
              - path: sys/kafka.js
                options:
                  uri: 127.0.0.1:2181
                  templates:
                    simple_test_rule:
                      topic: test_topic_simple_test_rule
                      retry_limit: 2
                      retry_delay: 10
                      retry_on:
                        status:
                          - '50x'
                          - 400
                      match:
                        message: 'test'
                      exec:
                        method: post
                        uri: 'http://mock.com'
                        headers:
                          test_header_name: test_header_value
                          content-type: application/json
                        body:
                          test_field_name: test_field_value
                          derived_field: '{{message.message}}'

                    kafka_producing_rule:
                      topic: test_topic_kafka_producing_rule
                      exec:
                        method: 'post'
                        uri: '/sys/queue/events'
                        body:
                          - meta:
                              topic: '{{message.produce_to_topic}}'
                            message: 'test'
                          - meta:
                              topic: '{{message.produce_to_topic}}'
                            message: 'test'