num_workers: 0
logging:
  name: changeprop
  level: info
services:
  - name: changeprop
    module: hyperswitch
    conf:
      port: 7273
      spec:
        x-sub-request-filters:
          - type: default
            name: http
            options:
              allow:
                - pattern: /^https?:\/\//
        title: The Change Propagation root
        paths:
          /sys/links:
            x-modules:
              - path: sys/backlinks.js
                options:
                  templates:
                    apiURITemplate: 'https://{{message.meta.domain}}/w/api.php'
          /sys/queue:
            x-modules:
              - path: sys/kafka.js
                options:
                  uri: 127.0.0.1:2181
                  consume_dc: test_dc
                  produce_dc: test_dc
                  templates:
                    simple_test_rule:
                      topic: simple_test_rule
                      retry_limit: 2
                      retry_delay: 10
                      retry_on:
                        status:
                          - '50x'
                          - 400
                      match:
                        message: 'test'
                      exec:
                        method: post
                        uri: 'http://mock.com'
                        headers:
                          test_header_name: test_header_value
                          content-type: application/json
                        body:
                          test_field_name: test_field_value
                          derived_field: '{{message.message}}'

                    process_redlinks:
                      topic: mediawiki.revision_create
                      retry_limit: 0
                      match:
                        rev_parent_id: undefined
                      exec:
                        method: post
                        uri: '/sys/links/backlinks/{message.title}'
                        body: '{{globals.message}}'

                    rerender_restbase:
                      topic: resource_change
                      match:
                        meta:
                          uri: '/https:\/\/([a-zA-Z0-9\.]+)\/wiki\/(.+)/'
                        tags: [ 'change-prop', 'backlinks' ]
                      exec:
                        method: get
                        uri: 'https://{{match.meta.uri[1]}}/api/rest_v1/page/html/{match.meta.uri[2]}'
                        headers:
                          cache-control: no-cache

                    kafka_producing_rule:
                      topic: kafka_producing_rule
                      exec:
                        method: 'post'
                        uri: '/sys/queue/events'
                        body:
                          - meta:
                              topic: '{{message.produce_to_topic}}'
                            message: 'test'
                          - meta:
                              topic: '{{message.produce_to_topic}}'
                            message: 'test'
